### ISSUE TITLE
Зачем здесь mvc?

### ISSUE THREAD

**Issue by SergeyKashkovsky** [Z3roTech/junior-webapi-task#1]
https://github.com/Z3roTech/junior-webapi-task/blob/01e585d4b15f3b90fda46fcd7001611321ce9b09/ST-JuniorProject/Startup.cs#L27

**Comment by Z3roTech** [comment]
Убрал MVC.

**Comment by SergeyKashkovsky** [comment]
Здесь также, ответь на вопрос.

**Comment by Z3roTech** [comment]
Изначально добавлял по примеру из учебного проекта, но теперь знаю, что подключение не было необходимо, т.к. при создании проекта был прописан `services.AddControllers();` который обеспечивает необходимыми сервисами для работы с контроллерами. Как я позже почитал `services.AddControllers();` позволяют использовать контроллеры без представления. Также изначально я прописал `services.AddMvc(); `  предполагая, что будет необходимо использовать View, но перечитав ТЗ и почитав документацию по ASP.Net WebApi и созданию Api-контроллеров понял, что во View нет необходимости.
