### ISSUE TITLE
EntityFramework не используется, зачем он присутствует во всем проекте?

### ISSUE THREAD

**Issue by SergeyKashkovsky** [Z3roTech/junior-webapi-task#2]
https://github.com/Z3roTech/junior-webapi-task/blob/01e585d4b15f3b90fda46fcd7001611321ce9b09/ST-JuniorProject/Services/Implementations/UserInfoUpdateService.cs#L21

**Comment by SergeyKashkovsky** [comment]
Вижу, используется, поторопился. В любом случае, в данном сервисе не используется, не?

**Comment by Z3roTech** [comment]
> Вижу, используется, поторопился. В любом случае, в данном сервисе не используется, не?

Убрал **DbContext** из приложения, теперь везде используются ХП. **EntityFramework** необходим для **SqlConnection**, т.к. проект находится на версии .Net Core 3.1, а поддержка SqlConnection без EF доступна до версии .Net Core 1.1 (включительно). https://docs.microsoft.com/ru-ru/dotnet/api/system.data.sqlclient.sqlconnection?view=netcore-1.1

**Comment by SergeyKashkovsky** [comment]
> а поддержка SqlConnection без EF доступна до версии .Net Core 1.1 (включительно)

Что имеется в виду под словом "поддержка" и откуда такая информация?

**Comment by Z3roTech** [comment]
Имеется в виду то, что в проекте на версии .NET Core 3.1 `System.Data.SqlClient` не содержится необходимого для работы DatabaseUtils, CrmUserInfoService и UserInfoService класса SqlConnection (в ссылке на документацию ниже, внизу страницы описаны версии применения), для текущей версии проекта SqlConnection содержится в `Microsoft.Data.SqlClient` (библиотека **Microsoft.EntityFrameworkCore.SqlServer**). Хотя **Microsoft.EntityFrameworkCore** можно удалить, т.к. она не требуются для работы **Microsoft.EntityFrameworkCore.SqlServer**.
