### ISSUE TITLE
Почему не из AppSettings.json взята строка подключения?

### ISSUE THREAD

**Issue by SergeyKashkovsky** [Z3roTech/junior-webapi-task#3]
https://github.com/Z3roTech/junior-webapi-task/blob/01e585d4b15f3b90fda46fcd7001611321ce9b09/ST-JuniorProject/Services/Implementations/UserInfoUpdateService.cs#L27

**Comment by Z3roTech** [comment]
Выполнил.

**Comment by SergeyKashkovsky** [comment]
Я бы все-таки хотел, чтобы ты на вопрос ответил

**Comment by SergeyKashkovsky** [comment]
И лучше не закрывать мои Issues

**Comment by Z3roTech** [comment]
Изначально прописал напрямую строку по нескольким причинам:
1.  Создание дополнительных классов для десериализации appsettings.json выглядело избыточным решением.
2.  Десериализация в `dynamic` класс выглядела для меня "небезопасной", т.к. среда разработки даже не сможет указать на ошибку, если она будет допущена или подсказать как правильно получить необходимые данные.
3.  Считывать как строку и искать при помощи операций над строкой (Split, Contains, Substring и т.д.) было совсем плохим, на мой взгляд, решением

Лишь позже я смог осознать, что можно передать IConfiguration в необходимые классы и из него получить строку подключения, что в итоге и сделал.
