### ISSUE TITLE
Нет ни одного комментария

### ISSUE THREAD

**Issue by SergeyKashkovsky** [Z3roTech/junior-webapi-task#4]
Ко всем классам, свойствам, полям и методам нужно добавить комментарий, для чего и зачем. Пример - в том классе, который я тебе передал:

 /// &lt;summary&gt;   
 /// Утилиты для работы с курсором, который возвращает SQLCommand.ExecuteReader    
/// &lt;/summary&gt;    
public static class DatabaseUtils

**Comment by Z3roTech** [comment]
> Ко всем классам, свойствам, полям и методам нужно добавить комментарий, для чего и зачем. Пример - в том классе, который я тебе передал:
> 
> /// <summary>
> /// Утилиты для работы с курсором, который возвращает SQLCommand.ExecuteReader
> /// </summary>
> public static class DatabaseUtils

Все классы, методы и свойства были прокомментированы.
