### ISSUE TITLE
Нет ХП `spReadUserByLogin`

### ISSUE THREAD

**Issue by SergeyKashkovsky** [Z3roTech/junior-webapi-task#5]
Создай папку SQL в проекте и положи туда SQL код ХП

**Comment by Z3roTech** [comment]
Все SQL запросы на создание CRUD ХП находятся в папке SQL. Также поместил туда сгенерированные запросы на создание БД и таблиц.

- CRUD <Название таблицы> - содержит Create, Read, Update и Delete ХП для указанной таблицы;
- SQLCreate<Объект> - сгенерированные при помощи SQL Server Management Studio запросы на создание БД или таблицы.
